plugins {
    id 'java-library'
    id 'java-test-fixtures'
}

description = 'inventory bounded context'

dependencies {
    api project(':inventory:inventory-api')
    api project(':archone-framework:foundation')
    api project(':orchestration-temporal-contract')
    api project(':archone-framework:messaging:messaging-consumer-common')
    api project(':archone-framework:messaging:messaging-events')
    api project(':archone-framework:messaging:messaging-spring-optimistic-locking')
    api libs.spring.boot.starter.data.jpa
    api libs.spring.boot.starter.webmvc

    implementation project(':archone-framework:domain-contract')
    implementation project(':integration-contracts')
    implementation project(':archone-framework:messaging:messaging-spring-boot-autoconfigure')
    implementation libs.micrometer.core
    implementation libs.spring.boot.starter.actuator
    implementation libs.spring.boot.starter.jdbc
    implementation libs.spring.boot.starter.validation

    testImplementation project(':spring-framework-support')
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.boot.starter.webmvc.test
    testRuntimeOnly libs.junit.platform.launcher
}
