rootProject.name = 'archone'

include('bootstrap')
include('ordering-context')
include('inventory-context')
include('logistics-data-context')
include('order-fulfillment-workflow')
include('wms')
include('wms-runtime')
include('foundation')
include('contracts')

apply from: file('messaging/messaging.settings.gradle')
