rootProject.name = 'archone'

include('deployments:monolith')
include('ordering-context')
include('inventory-context')
include('logistics-data-context')
include('fulfillment-process')
include('orchestration-temporal-contract')
include('orchestration-temporal-runtime')
include('wms-context')
include('foundation')
include('domain-contract')
include('spring-framework-support')
include('integration-contracts')

apply from: file('messaging/messaging.settings.gradle')
