spring.application.name=wms-runtime
spring.main.web-application-type=none
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/wms/migration
spring.jpa.hibernate.ddl-auto=none
spring.kafka.bootstrap-servers=${WMS_KAFKA_BOOTSTRAP_SERVERS:localhost:28292}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.listener.missing-topics-fatal=false
