spring.datasource.url=${WMS_DB_URL:jdbc:postgresql://localhost:28291/wms}
spring.datasource.username=${WMS_DB_USERNAME:wms}
spring.datasource.password=${WMS_DB_PASSWORD:wms}
spring.flyway.enabled=true
