plugins {
    id 'java-library'
}

description = 'framework-neutral JDBC Inbox duplicate detection and transactional handling'

dependencies {
    api project(':messaging:messaging-consumer-common')
    api project(':messaging:messaging-jdbc-common')

    testImplementation libs.spring.boot.starter.test
    testRuntimeOnly libs.junit.platform.launcher
}
