spring.datasource.url=${ORDER_PROMISING_DB_URL:jdbc:postgresql://localhost:5432/order_promising}
spring.datasource.username=${ORDER_PROMISING_DB_USERNAME:order_promising}
spring.datasource.password=${ORDER_PROMISING_DB_PASSWORD:order_promising}
