plugins {
    id 'java-library'
}

description = 'ordering bounded context'

dependencies {
    api project(':ordering:ordering-api')
    api project(':archone-framework:foundation')
    api project(':orchestration-temporal-contract')
    api project(':archone-framework:messaging:messaging-events')
    api libs.spring.boot.starter.data.jpa
    api libs.spring.boot.starter.webmvc

    implementation project(':integration-contracts')
    implementation project(':archone-framework:messaging:messaging-spring-boot-autoconfigure')
    implementation libs.spring.boot.starter.validation

    testImplementation 'com.tngtech.archunit:archunit-junit5:1.5.0'
    testImplementation project(':spring-framework-support')
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.boot.starter.webmvc.test
    testRuntimeOnly libs.junit.platform.launcher
}
