plugins {
    id 'java-library'
}

description = 'wms'

dependencies {
    api project(':wms:wms-api')
    implementation project(':archone-framework:foundation')
    implementation project(':orchestration-temporal-contract')
    implementation project(':integration-contracts')
    implementation project(':archone-framework:messaging:messaging-events')
    implementation project(':archone-framework:messaging:messaging-spring-boot-autoconfigure')
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.webmvc

    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.boot.starter.webmvc.test
    testRuntimeOnly libs.junit.platform.launcher
}
