plugins {
    alias(libs.plugins.java)
}

description = 'wms'

dependencies {
    implementation project(':foundation')
    implementation project(':integration-contracts')
    implementation project(':fulfillment-workflow-contract')
    implementation project(':messaging:messaging-events')
    implementation project(':messaging:messaging-spring-boot-autoconfigure')
    implementation libs.spring.boot.starter.data.jpa

    testImplementation libs.spring.boot.starter.test
    testRuntimeOnly libs.junit.platform.launcher
}
