plugins {
    id 'java-library'
}

description = 'framework-neutral JDBC Outbox message producer implementation'

dependencies {
    api project(':messaging:messaging-producer-common')
    api project(':messaging:messaging-jdbc-common')
    api libs.jackson.databind

    testImplementation libs.spring.boot.starter.test
    testRuntimeOnly libs.junit.platform.launcher
}
