plugins {
    id 'java-library'
}

description = 'legacy Inbox API and JPA migration bridge'

dependencies {
    api project(':messaging:messaging-api')
    api project(':messaging:messaging-consumer-common')
    api project(':messaging:messaging-jdbc-common')
    implementation libs.spring.boot.starter.data.jpa

    testImplementation libs.spring.boot.starter.test
    testRuntimeOnly libs.junit.platform.launcher
}
