plugins {
    id 'java-library'
}

description = 'Spring Boot auto-configuration for Archone transactional messaging'

dependencies {
    api project(':messaging:messaging-api')
    api project(':messaging:messaging-events')
    api project(':messaging:messaging-producer-common')
    api project(':messaging:messaging-consumer-common')
    api project(':messaging:messaging-producer-jdbc')
    api project(':messaging:messaging-consumer-jdbc')
    api project(':messaging:messaging-producer-outbox')
    api project(':messaging:messaging-consumer-inbox')
    api project(':messaging:messaging-consumer-kafka')
    api project(':messaging:messaging-spring-producer-jdbc')
    api project(':messaging:messaging-spring-consumer-jdbc')

    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.kafka
    implementation libs.jackson.datatype.jsr310

    testImplementation libs.spring.boot.starter.test
    testRuntimeOnly libs.junit.platform.launcher
}
